# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  #vmImage: 'ubuntu-latest'
  name: Inqubator
  demands:
   - agent.name -equals heu2hubazuredevopsagent
  
container: gitlab.qpidhealth.net:4567/devops/ci/java:openjdk-8u181_mvn_1

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenVersionOption: 'Path'
    mavenDirectory: '/usr/local/src/apache-maven'
    mavenSetM2Home: true
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    jdkDirectory: '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
